### ISSUE TITLE
webkit scroll bar interfering with global styles

### ISSUE THREAD

**Issue by MichaelOdumosu57** [near/wallet-selector#627]
**Describe the bug**

this is affecting my global styles  for scroll bar set in the application
![image](https://user-images.githubusercontent.com/21322737/210821086-38720720-dac8-439f-b490-81092baa4920.png)
see how the previous css rules are contined to the  root selector becuase of the suffix, well not on the scroll bar  this needs to be fixed

**Expected behavior**

```css
.nws-modal-wrapper  ::-webkit-scrollbar  {
        height: 4px;
        width: 4px;
        background: var(--backdrop-bg);
}

  .nws-modal-wrapper   ::-webkit-scrollbar-thumb:horizontal {
        background: var(--close-button-fill-icon-color);
        border-radius: 10px;
    }
```

**Screenshots**

**Device (please complete the following information):**

**Additional context**
